Sensible defaults
conversation/i18n-hygiene pull request #30
Opened 2017-07-20 02:35 UTC by keithpitty

This PR introduces the use of the `available_locales` from the global `I18n` object as a default for the configurable locales. It also takes the opportunity to refactor the derivation of `all_locales` that is used in several checks.

2017-07-20 02:36 UTC, keithpitty commented
![](https://github.trello.services/images/mini-trello-icon.png) [[i18n-hygiene] Set sensible defaults for config options](https://trello.com/c/3vLrWipS/7810-i18n-hygiene-set-sensible-defaults-for-config-options)

2017-07-20 04:41 UTC, eleanorakh commented
After reading a bit about protected methods, [here](https://tenderlovemaking.com/2012/09/07/protected-methods-and-ruby-2-0.html) and [here](http://nithinbekal.com/posts/ruby-protected-methods/) I think this is a reasonable change. That said, another set of eyes would be appreciated prior to merge!

2017-07-21 00:22 UTC, nullobject requested changes

2017-07-21 00:22 UTC, nullobject commented on lib/i18n/hygiene/config.rb
> +      attr_reader :all_locales
I don't think you need to add `all_locals` as an `attr_reader` since you already defined a method on line 25.

2017-07-21 00:22 UTC, nullobject commented on lib/i18n/hygiene/checks/base.rb
> +        protected
Very appropriate 👍

2017-07-21 01:12 UTC, keithpitty commented
@nullobject thanks for picking up that unnecessary `attr_reader`. Removed.

2017-07-21 01:13 UTC, nullobject approved these changes

2017-07-21 01:14 UTC, merged